### ISSUE TITLE
I tried build this on Apache2.

### ISSUE THREAD

**Issue by Rei-Nanao** [GenbuProject/SimpleThread#26]
どうも。まず私はapache2を使用したうえでSTを立ち上げてみました。
以下がその結果です。
[https://st.nature.0j0.jp](https://st.nature.0j0.jp)
ここでまず私が提示したいのは
  何故レイアウトが崩れてしまうのか(おそらく絶対パスで設定しているのでは？)
今の所実用は難しいです。
以下に実際にapache2で使用したconfigファイルを掲載します。

> st.conf
`<VirtualHost *:80>
   DocumentRoot /var/www/html/SimpleThread
   ServerName example.com

ErrorDocument 404 /var/www/html/SimpleThread/404.html
ErrorDocument 401 /var/www/html/SimpleThread/Error/401/index.html
ErrorDocument 403 /var/www/html/SimpleThread/Error/403.10/
ErrorDocument 406 /var/www/html/SimpleThread/Error/406/index.html
RewriteEngine on
RewriteCond %{SERVER_NAME} =example.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>`

> st-le-ssl.conf
`<IfModule mod_ssl.c>
<VirtualHost *:443>
   DocumentRoot /var/www/html/SimpleThread
   ServerName example.com

ErrorDocument 404 /var/www/html/SimpleThread/404.html
ErrorDocument 401 /var/www/html/SimpleThread/Error/401/index.html
ErrorDocument 403 /var/www/html/SimpleThread/Error/403.10/
ErrorDocument 406 /var/www/html/SimpleThread/Error/406/index.html
SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>`

**Comment by GenbuHase** [comment]
プルリクありがとうございます。
そうですね、現在は全て`/SimpleThread/`で指定してあるので、grepなどで置換してもらうしか方法がないのが現状です。

先日PS4から閲覧して正常な動作が確認されなかったので、もう1度組み込み部分を書きなおすつもりでいます。
報告ありがとうございました。
